#log-path = "./logs"
#http-port = 8199
api-prefix = "api"
debug = true
# 基本服务配置
[server]
    Address          = ":9000"
    ServerRoot       = "public"
    LogPath          = "./logs"
#    IndexFiles       = ["index.html"]
    AccessLogEnabled = true  # 服务成功日志是否打印打印，默认false
    ErrorLogEnabled  = true
    PProfEnabled     = true
#    SessionIdName    = "MySessionId"
#    SessionPath      = "/tmp/MySessionStoragePath"
#    SessionMaxAge    = "24h"
    DumpRouterMap    = true

# title设置
[setting]
    title = "配置管理中心"

# 数据库配置
[database]
    link = "mysql:root:root@tcp(127.0.0.1:3306)/myProject"

# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,1"

#jwt配置
[gToken]
    CacheMode = 2
    CacheKey = "GToken:"
    Timeout = 0
    MaxRefresh = 0
    TokenDelimiter="_"
    EncryptKey = "fghfdghzdfgdfgdfer34535~!@234"
    AuthFailMsg = "登录超时，请重新登录"
    MultiLogin = false

# 日志配置
[logger]
    path   = "/var/log"
    level  = "all"
    stdout = true

# 编译配置
[compiler]
    name     = "my-app"
    version  = "1.0.0"
    arch     = "386,amd64"
    system   = "linux,windows,darwin"
    output   = ""
    path     = "./bin"
    extra    = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
#    [compiler.VarMap]
#        author = "duanhaobin"
#        email  = "john@goframe.org"
