// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"fmt"
	"go-projects-server/internal/app/user/controller"
	"go-projects-server/internal/app/user/dao"
	"go-projects-server/internal/app/user/service"
	"go-projects-server/pkg/conf"
	"go-projects-server/pkg/database"
	"go-projects-server/pkg/log"

	"github.com/google/wire"
)

// Injectors from wire.go:

func initWebApp() (*WebApp, error) {
	config, err := conf.Init()
	if err != nil {
		fmt.Println("conf init failed,err:", err)
		return nil, err
	}
	engine, err := InitEngine(config)
	if err != nil {
		fmt.Println("engine init failed,err:", err)
		return nil, err
	}
	if err = log.Init(config); err != nil {
		fmt.Println("log init failed,err:", err)
		return nil, err
	}
	db := database.Init(config)
	userDao := &dao.UserDao{
		DB: db,
	}
	userService := &service.UserService{
		Dao: userDao,
	}
	userController, err := controller.NewUseController(engine, userService)
	if err != nil {
		return nil, err
	}
	webApp := &WebApp{
		Engine: engine,
		config: config,
		user:   userController,
	}
	return webApp, nil
}

// wire.go:

var controllerSet = wire.NewSet(controller.NewUseController)
